version: '3.9'
services:
  fastifybeej:
    image: fastifybeej
    env_file:
      - .env
      - .env.development
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - $PORT:$PORT
      - $DEBUG_PORT:$DEBUG_PORT
    # We are installing yarn again to sync node_modules with the host
    # You ca remove the re-installation command and use VSCode remote containers
    command: sh -cx 'yarn install --frozen-lockfile --silent && yarn start:dev'
