version: '3.9'
services:
  fastify-beej:
    image: ${DOCKER_HUB_USERNAME}/fastify-beej
    env_file:
      - .env
      - .env.production
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
