version: '3.4'

services:
  fastifybeej:
    image: fastifybeej
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
