version: '3.4'

services:
  fastifybeej:
    image: fastifybeej
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: ['yarn', 'debug']
