version: '3.4'

services:
  fastifybeej:
    image: fastifybeej
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: ${NODE_ENV} # from .env file
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: ['yarn', 'start:dev']
