version: '3.9'
services:
  fastifybeej:
    image: fastifybeej
    env_file:
      - .env
      - .env.development
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/usr/app
      # - ./node_modules:/usr/app/node_modules
    ports:
      - $PORT:$PORT
      - $DEBUG_PORT:$DEBUG_PORT
    command: sh -cx 'yarn && yarn start:dev'
