version: '3.9'
services:
  mongodb-dev:
    image: mongo:5-focal
    container_name: $MONGODB_DATABASE_HOSTNAME
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - $MONGODB_PORT:$MONGODB_PORT
    volumes:
      - .mongodb_data:/data/db
      - .mongodb_data/mongodb_config:/data/configdb
  fastify-beej:
    image: ${DOCKER_HUB_USERNAME}/fastify-beej
    environment:
      - MONGODB_DATABASE_URI="mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@$MONGODB_DATABASE_HOSTNAME:$MONGODB_PORT"
    env_file:
      - .env
      - .env.development
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - .:/usr/app
    restart: unless-stopped
    ports:
      - $PORT:$PORT
      - $DEBUG_PORT:$DEBUG_PORT
    # We are installing node_modules again to sync node_modules with the host.
    # node_modules in the host system helps with linting and intellisense.
    # The 1st time it builds the container, it might be slow.
    # Consecutive runs would be faster.
    # If you aren't happy with the re-installation step, you can remove the
    # `yarn install` command and use VSCode remote containers extension
    command: sh -cx 'yarn install --frozen-lockfile --silent && yarn start:dev'
    depends_on:
      - $MONGODB_DATABASE_HOSTNAME
