# Name of our workflow
name: CI pipeline

# Event at which we wanna run our actions
on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

# Jobs help us group the steps to run
jobs:
  # Name of the job
  verify-and-push-image-to-docker-hub:
    # The operating system to use for running the jobs
    runs-on: ubuntu-latest
    # List the steps to run in succession
    steps:
      # checks-out our repository under $GITHUB_WORKSPACE, so our workflow can access it
      - name: GitHub Checkout v2
        uses: actions/checkout@v2

      - name: Build and push (with cache)
        id: build-and-push-with-cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          compose_file: docker-compose.yml
          build_extra_args: '--compress=true'

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
